version: '3'
services:
  sync:
    image: waisbrot/wait
    links:
      - ari
      - auth
      - ctid-ng
      - mongooseim
      - postgres
      - rabbitmq
    environment:
      - TARGETS=ari:5039,postgres:5432,rabbitmq:5672,mongooseim:8088,auth:9497,ctid-ng:9500,ctid-ng:9501
      - TIMEOUT=${INTEGRATION_TEST_TIMEOUT}

  ari:
    image: ari-mock
    ports:
      - 5039
    volumes:
      - ./ari:/usr/local/share/ari
      - ./ssl/ari:/usr/local/share/ari-ssl
    environment:
      - PYTHONPATH=/usr/local/share/ari
    command: gunicorn -b 0.0.0.0:5039 -k flask_sockets.worker mock_ari:app

  auth:
    image: p0bailey/docker-flask
    ports:
      - 9497
    volumes:
      - ./xivo-auth:/usr/local/share/xivo-auth
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/xivo-auth/mock-xivo-auth.py 9497

  ctid-ng:
    image: xivo-ctid-ng-test
    volumes:
      - ../../..:/usr/src/xivo-ctid-ng
      - ./etc/xivo-ctid-ng:/etc/xivo-ctid-ng
      - ./ssl:/usr/local/share/ssl
    links:
      - ari
    ports:
      - 9500
    expose:
      - 9501
    environment:
      - XIVO_UUID=08c56466-8f29-45c7-9856-92bf1ba89b92

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672

  mongooseim:
    image: mongooseim/mongooseim:latest
    hostname: mongooseim-1
    expose:
      - 8088
    volumes:
      - ./etc/mongooseim:/member
      - ./mongooseim:/tmp/mongooseim

  postgres:
    image: postgres:9.4
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mongooseim
    volumes:
      - ./mongooseim/pg.sql:/docker-entrypoint-initdb.d/pg.sql
