sync:
  image: n3llyb0y/wait
  links:
    - ari
    - ctid-ng
    - swagger-validator
  environment:
    PORTS: "5039 9500 8080"

ctid-ng:
  image: xivo-ctid-ng-test
  volumes:
    - "../../..:/usr/src/xivo-ctid-ng"
    - "./etc/xivo-ctid-ng:/etc/xivo-ctid-ng"
    - "./ssl:/usr/local/share/ssl"
  ports:
    - "9500"
  environment:
    XIVO_UUID: "08c56466-8f29-45c7-9856-92bf1ba89b92"
  links:
    - ari

ari:
  image: ari-mock
  expose:
    - 5039
  volumes:
    - "./ari:/usr/local/share/ari"
    - "./ssl/ari:/usr/local/share/ari-ssl"
  environment:
    PYTHONPATH: "/usr/local/share/ari"
  command: "gunicorn -b 0.0.0.0:5039 -k flask_sockets.worker mock_ari:app"

swagger-validator:
  image: swaggerapi/swagger-validator
  ports:
    - "8080"
  links:
    - ctid-ng
