extra_config_files: /etc/xivo-ctid-ng/conf.d/

debug: false
logfile: /var/log/xivo-ctid-ng.log
pidfile: /var/run/xivo-ctid-ng.pid

rest_api:
  listen: 0.0.0.0
  port: 9500
  certificate: /usr/local/share/ssl/ctid-ng/server.crt
  private_key: /usr/local/share/ssl/ctid-ng/server.key
  cors:
    enabled: True
    allow_headers: [Content-Type, X-Auth-Token]

amid:
  host: amid
  port: 9491
  verify_certificate: /usr/local/share/ssl/amid/server.crt

ari:
  connection:
    base_url: http://ari:5039
    username: xivo
    password: Nasheow8Eag

auth:
  host: auth
  port: 9497
  timeout: 2
  verify_certificate: /usr/local/share/ssl/auth/server.crt
  key_file: /etc/xivo-ctid-ng/key.yml

bus:
  username: guest
  password: guest
  host: rabbitmq
  port: 5672

collectd:
  exchange_name: collectd

confd:
  host: confd
  port: 9486
  verify_certificate: /usr/local/share/ssl/confd/server.crt

consul:
  host: consul
  scheme: https
  verify: /usr/local/share/ssl/consul/server.crt

ctid:
  host: ctid
  port: 9495

websocketd:
  wss: False
  host: websocketd
  port: 9502
  verify_certificate: False

enabled_plugins:
  - calls
  - chats
  - presences
  - status
  - transfers
  - voicemails

service_discovery:
  enabled: false

remote_credentials:
  auth_not_registered:
    xivo_uuid: 582fbd45-73a3-41dd-9079-4c6d16fe1aad
    service_id: test
    service_key: idbehold
  invalid_credentials:
    xivo_uuid: 51400e55-2dc3-4cfc-a2f2-a4d4f0f8b217
    service_id: test
    service_key: foobar
  ctid_ng_not_registered:
    xivo_uuid: 196e42b9-bbfe-4c03-b3d4-684dffd01603
    service_id: test
    service_key: idbehold
  ctid_ng_invalid_credentials:
    xivo_uuid: 04b0087e-1661-4a42-8181-4b61e198204d
    service_id: test
    service_key: iddqd
  working:
    xivo_uuid: 5720ee16-61cc-412e-93c9-ae06fa0be845
    service_id: test
    service_key: 5ecr37

