version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - ari
      - confd
      - ctid-ng
      - rabbitmq
    environment:
      TARGETS: "ari:5039 ari:5040 rabbitmq:5672 confd:9486 auth:9497 ctid-ng:9500"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  ari:
    image: ari-real
    ports:
      - "5039"
    volumes:
      - "./etc/asterisk:/etc/asterisk"
      - "./ssl:/usr/local/share/ssl"
    command: "asterisk -fT"

  auth:
    image: wazopbx/xivo-auth-mock
    volumes:
      - "./ssl:/usr/local/share/ssl"

  confd:
    image: p0bailey/docker-flask
    volumes:
      - "./xivo-confd:/usr/local/share/xivo-confd"
      - "./ssl:/usr/local/share/ssl"
    command: "python /usr/local/share/xivo-confd/mock-xivo-confd.py 9486"

  ctid-ng:
    image: xivo-ctid-ng-test
    volumes:
      - "../../..:/usr/src/xivo-ctid-ng"
      - "./etc/xivo-ctid-ng:/etc/xivo-ctid-ng"
      - "./ssl:/usr/local/share/ssl"
    ports:
      - "9500"
    environment:
      XIVO_UUID: "08c56466-8f29-45c7-9856-92bf1ba89b92"

  rabbitmq:
    image: rabbitmq
