version: '3'
services:
  sync:
    image: n3llyb0y/wait
    links:
      - amid
      - ari
      - auth
      - confd
      - consul
      - ctid
      - ctid-ng
      - rabbitmq
      - remote_ctid_ng
    environment:
      - PORTS=5039 5672 8500 9486 9491 9495 9497 9500 9501
      - TIMEOUT=${INTEGRATION_TEST_TIMEOUT}

  amid:
    image: p0bailey/docker-flask
    ports:
      - 9491
    volumes:
      - ./xivo-amid:/usr/local/share/xivo-amid
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/xivo-amid/mock-xivo-amid.py 9491

  ari:
    image: ari-mock
    ports:
      - 5039
    volumes:
      - ./ari:/usr/local/share/ari
      - ./ssl/ari:/usr/local/share/ari-ssl
    environment:
      - PYTHONPATH=/usr/local/share/ari
    command: gunicorn -b 0.0.0.0:5039 -k flask_sockets.worker mock_ari:app

  auth:
    image: p0bailey/docker-flask
    ports:
      - 9497
    volumes:
      - ./xivo-auth:/usr/local/share/xivo-auth
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/xivo-auth/mock-xivo-auth.py 9497

  ctid:
    image: p0bailey/docker-flask
    expose:
      - 9495
    volumes:
      - ./xivo-ctid:/usr/local/share/xivo-ctid
    command: python /usr/local/share/xivo-ctid/mock-xivo-ctid.py 9495

  confd:
    image: p0bailey/docker-flask
    ports:
      - 9486
    volumes:
      - ./xivo-confd:/usr/local/share/xivo-confd
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/xivo-confd/mock-xivo-confd.py 9486

  consul:
    image: p0bailey/docker-flask
    ports:
      - 8500
    volumes:
      - ./consul:/usr/local/share/consul
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/consul/mock-consul.py 8500

  ctid-ng:
    image: xivo-ctid-ng-test
    volumes:
      - ../../..:/usr/src/xivo-ctid-ng
      - ./etc/xivo-ctid-ng:/etc/xivo-ctid-ng
      - ./ssl:/usr/local/share/ssl
    ports:
      - 9500
    expose:
      - 9501
    environment:
      - XIVO_UUID=08c56466-8f29-45c7-9856-92bf1ba89b92

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672

  remote_ctid_ng:
    image: p0bailey/docker-flask
    ports:
      - 9501
    volumes:
      - ./xivo-ctid-ng:/usr/local/share/ctid-ng
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/ctid-ng/ctid-ng-mock.py 9501
