version: '3.7'
services:
  sync:
    depends_on:
      - ari
      - calld
      - swagger-validator
    environment:
      TARGETS: "ari:5039 calld:9500 swagger-validator:8080"

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
