version: '3.7'
services:
  sync:
    depends_on:
      - amid
      - ari
      - auth
      - confd
      - consul
      - calld
      - rabbitmq
      - websocketd
    environment:
      TARGETS: "ari:5039 rabbitmq:5672 consul:8500 confd:9486 amid:9491 auth:9497 calld:9500 websocketd:9502"
