version: '3.7'
services:
  sync:
    image: waisbrot/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  amid:
    image: p0bailey/docker-flask
    ports:
      - 9491
    volumes:
      - ./xivo-amid:/usr/local/share/xivo-amid
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/xivo-amid/mock-xivo-amid.py 9491

  ari:
    image: ari-mock
    ports:
      - 5039
    volumes:
      - ./ari:/usr/local/share/ari
      - ./ssl/ari:/usr/local/share/ari-ssl
    environment:
      PYTHONPATH: /usr/local/share/ari
    command: gunicorn -b 0.0.0.0:5039 -k flask_sockets.worker mock_ari:app

  auth:
    image: wazopbx/xivo-auth-mock
    ports:
      - 9497
    volumes:
      - ./ssl:/usr/local/share/ssl

  ctid:
    image: p0bailey/docker-flask
    expose:
      - 9495
    volumes:
      - ./xivo-ctid:/usr/local/share/xivo-ctid
    command: python /usr/local/share/xivo-ctid/mock-xivo-ctid.py 9495

  confd:
    image: p0bailey/docker-flask
    ports:
      - 9486
    volumes:
      - ./xivo-confd:/usr/local/share/xivo-confd
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/xivo-confd/mock-xivo-confd.py 9486

  consul:
    image: p0bailey/docker-flask
    ports:
      - 8500
    volumes:
      - ./consul:/usr/local/share/consul
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/consul/mock-consul.py 8500

  ctid-ng:
    image: xivo-ctid-ng-test
    volumes:
      - ../..:/usr/src/xivo-ctid-ng
      - ./ssl:/usr/local/share/ssl
      - ./etc/xivo-ctid-ng/key.yml:/etc/xivo-ctid-ng/key.yml
      - ./etc/xivo-ctid-ng/conf.d/50-base.yml:/etc/xivo-ctid-ng/conf.d/50-base.yml
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python2.7/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python2.7/site-packages/xivo_bus"
    ports:
      - 9500
    environment:
      XIVO_UUID: 08c56466-8f29-45c7-9856-92bf1ba89b92

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  remote_ctid_ng:
    image: p0bailey/docker-flask
    ports:
      - 9501
    volumes:
      - ./xivo-ctid-ng:/usr/local/share/ctid-ng
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/ctid-ng/ctid-ng-mock.py 9501

  websocketd:
    image: xivo-websocketd-mock
    ports:
      - 9502
    volumes:
      - ./xivo-websocketd:/usr/local/share/websocketd
    environment:
      PYTHONPATH: /usr/local/share/websocketd
    command: gunicorn -b 0.0.0.0:9502 -k flask_sockets.worker mock_websocketd:app
