version: '3'
services:
  sync:
    depends_on:
      - ari
      - auth
      - ctid-ng
      - rabbitmq
    environment:
      TARGETS: "ari:5039 rabbitmq:5672 auth:9497 ctid-ng:9500"

  ctid-ng:
    volumes:
      - ./etc/xivo-ctid-ng/conf.d/config.quick_ari_reconnect.yml:/etc/xivo-ctid-ng/conf.d/config.yml
