version: '3'
services:
  sync:
    depends_on:
      - amid
      - ari
      - auth
      - confd
      - consul
      - ctid
      - ctid-ng
      - rabbitmq
      - remote_ctid_ng
      - websocketd
    environment:
      TARGETS: "ari:5039 rabbitmq:5672 consul:8500 confd:9486 amid:9491 ctid:9495 auth:9497 ctid-ng:9500 remote_ctid_ng:9501 websocketd:9502"
