version: '3'
services:
  sync:
    depends_on:
      - ari
      - auth
      - ctid-ng
    environment:
      TARGETS: "ari:5039 auth:9497 ctid-ng:9500"

  ctid-ng:
    volumes:
      - ./etc/xivo-ctid-ng/conf.d/config.no_rabbitmq.yml:/etc/xivo-ctid-ng/conf.d/config.yml
