version: '3'
services:
  sync:
    depends_on:
      - ari
      - ctid-ng
      - rabbitmq
    environment:
      TARGETS: "ari:5039 rabbitmq:5672"

  ctid-ng:
    volumes:
      - ./etc/xivo-ctid-ng/conf.d/config.no_ssl_private_key.yml:/etc/xivo-ctid-ng/conf.d/config.yml
