version: '3.7'
services:
  sync:
    depends_on:
      - ari
      - calld
      - rabbitmq
    environment:
      TARGETS: "ari:5039 rabbitmq:5672"

  calld:
    volumes:
      - ./etc/wazo-calld/conf.d/20-invalid-ssl-key.yml:/etc/wazo-calld/conf.d/20-invalid-ssl-key.yml
